export const QUERY_KEY = {
    ACCOUNT: 'accounts',
    ACTIVITY: 'activities',
    AUTH: 'auth',
    CONTACT: 'contacts',
    COMMUNICATION: 'communications',
    DOCUMENT: 'documents',
    DROPDOWN: 'dropdowns',
    INVOICE: 'invoices',
    LEAD: 'leads',
    OPPORTUNITY: 'opportunities',
    PRODUCT_ORDER: 'product_orders',
    QUOTATION: 'quotations',
    ROLE: 'roles',
    SALES_ORDER: 'sales_orders',
    TASK: 'tasks',
    TICKET: 'tickets',
    USER: 'users',
    USER_MANAGEMENT: 'user_management',
    DROPDOWN_CATEGORIES: 'dropdown_categories',
    INVENTORY: 'inventory',
    INVENTORY_PRODUCT: 'inventory_products',
    INVENTORY_SERIAL_NUMBER: 'inventory_serial_numbers',
    INVENTORY_MOVEMENT: 'inventory_movements',
    CREDITS: 'credits',
}