import { EntityType } from "@/types/common";
import Typography from "./common/Typography";
import Page, { PageHeader, PageFooter } from "./Page";
import AiInsightsImg from "@/assets/ai_insights.svg?react";

type AiInsightsProps = {
  entityName: string;
  entityId: string;
  entityType: EntityType;
};
function AiInsights({ entityName, entityId, entityType }: AiInsightsProps) {
  return (
    <Page
      header={<PageHeader title="AI Insights" />}
      footer={
        <PageFooter>
          <Typography
            variant="body2"
            className="text-muted-foreground text-center text-xs"
          >
            Generated by AI Insights for {entityName} ({entityId})
          </Typography>
        </PageFooter>
      }
    >
      {/* Content */}
      <div className="flex-1 space-y-5">
        <div className="text-center text-muted-foreground">
          <p className="text-sm">
            AI Insights are generated based on your{" "}
            {entityType?.toLocaleLowerCase()}s' data.
          </p>
          <p className="text-sm">Insights will be available soon.</p>
        </div>
        <div className="flex items-center justify-center h-full ">
          <AiInsightsImg className="w-1/2 h-1/2 text-primary" />
        </div>
      </div>
    </Page>
  );
}

export default AiInsights;
