export const defaultValues = {
  orderNumber: "",
  orderDate: "",
  deliveryDate: "",
  accountId: "",
  opportunityId: "",
  billingAddress: "",
  billingCity: "",
  billingState: "",
  billingZip: "",
  billingCountry: "",
  shippingAddress: "",
  shippingCity: "",
  shippingState: "",
  shippingZip: "",
  shippingCountry: "",
  sameAsBilling: false,
  notes: "",
  lineItems: [defaultLineItems],
};